"""'test'

Revision ID: 1445d655c7d1
Revises: 6eac006ae994
Create Date: 2023-02-20 12:07:26.568794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1445d655c7d1'
down_revision = '6eac006ae994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('access')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('access', ['access'], unique=False)

    # ### end Alembic commands ###
