"""empty message

Revision ID: 1824ac1f59e4
Revises: 928051b72661
Create Date: 2023-02-24 11:59:35.400232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1824ac1f59e4'
down_revision = '928051b72661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payslips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_cut_off', sa.Date(), nullable=False),
    sa.Column('end_cut_off', sa.Date(), nullable=False),
    sa.Column('days_present', sa.Integer(), nullable=False),
    sa.Column('regular_hours', sa.Float(precision=2, asdecimal=True), nullable=False),
    sa.Column('ot_hours', sa.Float(precision=2, asdecimal=True), nullable=False),
    sa.Column('gross_pay', sa.Float(precision=2, asdecimal=True), nullable=False),
    sa.Column('deductions', sa.Float(precision=2, asdecimal=True), nullable=False),
    sa.Column('net_pay', sa.Float(precision=2, asdecimal=True), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payslips')
    # ### end Alembic commands ###
