"""empty message

Revision ID: 3652f00cd373
Revises: 75615d2e2aa0
Create Date: 2023-02-24 16:13:05.336272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3652f00cd373'
down_revision = '75615d2e2aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=500), nullable=False))

    # ### end Alembic commands ###
