"""empty message

Revision ID: 4e0cf9cee92c
Revises: 1824ac1f59e4
Create Date: 2023-02-24 12:02:52.828037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e0cf9cee92c'
down_revision = '1824ac1f59e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_regular_hours', sa.Float(precision=2, asdecimal=True), nullable=False))
        batch_op.add_column(sa.Column('pre_ot_hours', sa.Float(precision=2, asdecimal=True), nullable=False))
        batch_op.add_column(sa.Column('post_ot_hours', sa.Float(precision=2, asdecimal=True), nullable=False))
        batch_op.add_column(sa.Column('total_ot_hours', sa.Float(precision=2, asdecimal=True), nullable=False))
        batch_op.drop_column('regular_hours')
        batch_op.drop_column('ot_hours')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ot_hours', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('regular_hours', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('total_ot_hours')
        batch_op.drop_column('post_ot_hours')
        batch_op.drop_column('pre_ot_hours')
        batch_op.drop_column('total_regular_hours')

    # ### end Alembic commands ###
