"""empty message

Revision ID: 51f1147cfbd1
Revises: 9e37dcada82b
Create Date: 2023-02-23 13:12:47.789981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51f1147cfbd1'
down_revision = '9e37dcada82b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_rate', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('hourly_rate', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('bir_tax', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sss_tax', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('phil_health_tax', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('pag_ibig_tax', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ot_rate', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('allowance', sa.Integer(), nullable=False))
        batch_op.drop_column('amount')
        batch_op.drop_column('per_hour')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('per_hour', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('allowance')
        batch_op.drop_column('ot_rate')
        batch_op.drop_column('pag_ibig_tax')
        batch_op.drop_column('phil_health_tax')
        batch_op.drop_column('sss_tax')
        batch_op.drop_column('bir_tax')
        batch_op.drop_column('hourly_rate')
        batch_op.drop_column('daily_rate')

    # ### end Alembic commands ###
