"""empty message

Revision ID: 7a78707d1142
Revises: 4e0cf9cee92c
Create Date: 2023-02-24 12:40:36.691566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a78707d1142'
down_revision = '4e0cf9cee92c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
