"""empty message

Revision ID: fdb272058877
Revises: 7a78707d1142
Create Date: 2023-02-24 12:42:09.263412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb272058877'
down_revision = '7a78707d1142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowance', sa.Float(precision=2, asdecimal=True), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.drop_column('allowance')

    # ### end Alembic commands ###
